//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalAjanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeller()
        {
            this.Is_Detay = new HashSet<Is_Detay>();
            this.Izindekiler = new HashSet<Izindekiler>();
        }
    
        public int Personel_ID { get; set; }
        public Nullable<int> Derpartman_ID { get; set; }
        public string Sifre { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Bas_Harfler { get; set; }
        public Nullable<System.DateTime> Dogum_Tarihi { get; set; }
        public string E_Mail { get; set; }
        public string Telefon_No { get; set; }
        public string Vasfi { get; set; }
        public Nullable<System.DateTime> Ise_Giris_Tarihi { get; set; }
        public Nullable<int> Yillik_Izin_Gun_Sayisi { get; set; }
        public Nullable<bool> Admin { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Is_Detay> Is_Detay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izindekiler> Izindekiler { get; set; }
    }
}
